### ISSUE TITLE
manage content in subfolders ?

### ISSUE THREAD

**Issue by chrismade** [zipang/eidolon-labs#2]
I read your comments in netlify to 513 (content in subfolders) and 1156 (page tree manager) - and my view is exactly like yours - I wonder if you found a solution using forestry and metalsmith ? 
From the content in this repo it looks like there is still no solution ...

**Comment by zipang** [comment]
Hi @chrismade !
I'm really sorry i didn't notice your comment back then (in 2018) !
Well, yeah ! I didn't see any progress in the way Netlify CMS were going to handle subfolders in the content structure, because they didn't have a backend that would have provided information about the git repo structure for the CMS font end..
So indeed, Forestry.io is a better (git-based) headless CMS option in that regard for editing content in Markdown + Front Matter. 
I successgully used it with Metalsmith, or more recently with Gatsby as the static site generator.

**Comment by chrismade** [comment]
thanks for your reply - better late than never ;-) - I took on the challenge to adapt netlify-cms to Azure DevOps as another git-based repo so I understand now much better what's going on under the hood - and I will then review the subfolder topic as well as the _en/_fr/_de for translated pages once I have enough insights and no one else was faster - cannot promise any ETA yet - feel free to stop by at netlify-cms or my repo to check progress if you want - regards CM
